# Jekyll Config Keys
# https://jekyllrb.com/docs/configuration/options/
baseurl: ""
url: "https://gcr.me"

# Minima Config Keys
# https://github.com/jekyll/minima/blob/495703c59b1864158dafb4a2bb613ccc3d726fe9/_config.yml
title: gcr.me
author: Gerardo Ravago
email: gerardo@gcr.me
description: >-
  A personal homepage.
github_username: geedo0
linkedin_username: gerardo-ravago

# Build settings
theme: minima
plugins:
  - jekyll-feed
exclude:
  - README.md